[package]
name = "cgorganelle"
version = "0.1.0"
authors = ["Icaro Ferre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosc = "~0.3"